# Generated by Django 6.0.2 on 2026-02-27 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("participant_instructions", models.TextField(blank=True)),
                ("objective", models.TextField(blank=True)),
                ("context", models.TextField(blank=True)),
                ("hypotheses", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Not started (Planning)"),
                            ("COLLECTING", "Collecting diary entries"),
                            ("ANALYZING", "Analyzing diary entries"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                ("data_collection_start", models.DateTimeField(blank=True, null=True)),
                ("data_collection_end", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("EVENT_BASED", "Event-based"),
                            ("FREEFORM", "Freeform"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_studies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("LIKERT_7", "Likert (7-point)"),
                            ("SHORT_TEXT", "Short text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EVALUATOR", "Evaluator"),
                            ("PARTICIPANT", "Participant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="studies.study",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "likert_value",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("text_value", models.TextField(blank=True, null=True)),
                (
                    "diary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_responses",
                        to="studies.diaryentry",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="studies.prompt",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diary_entry", "prompt"), name="unique_prompt_per_entry"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 1)), name="prompt_order_gte_1"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(
                fields=["study", "participant", "created_at"],
                name="studies_dia_study_i_c0ab01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(
                fields=["user", "role"], name="studies_stu_user_id_548371_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(
                fields=["study", "role"], name="studies_stu_study_i_1fe7cf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studymembership",
            constraint=models.UniqueConstraint(
                fields=("study", "user"), name="unique_user_per_study"
            ),
        ),
    ]
