# Generated by Django 6.0.2 on 2026-06-28 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('prompt_type', models.CharField(choices=[('LIKERT_7', 'Likert (7-point)'), ('SHORT_TEXT', 'Short text')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, choices=[('EVALUATOR', 'Evaluator'), ('NLP', 'NLP Model'), ('LLM', 'LLM Model')], max_length=20, null=True)),
                ('examples', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canonical Issue',
                'verbose_name_plural': 'Canonical Issues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, choices=[('EVALUATOR', 'Evaluator'), ('NLP', 'NLP Model'), ('LLM', 'LLM Model')], max_length=20, null=True)),
                ('examples', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canonical Theme',
                'verbose_name_plural': 'Canonical Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('INTERNAL', 'ChronicleUX submission'), ('EXTERNAL', 'External submission imported into ChronicleUX')], default='INTERNAL', max_length=20)),
                ('participant_external_id', models.CharField(blank=True, max_length=255)),
                ('participant_display_name', models.CharField(blank=True, max_length=255)),
                ('participant_email', models.EmailField(blank=True, max_length=254)),
                ('sentiment_self_report', models.CharField(choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], help_text='How would you describe your overall experience sentiment for this entry?', max_length=20)),
                ('issue_encountered', models.BooleanField(help_text='Did you encounter any issue or friction during this experience?')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Diary Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('raw_sentiment_result', models.JSONField(blank=True, default=list)),
                ('participant_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('participant_confusion_matrix_outcome', models.CharField(choices=[('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('TRUE_NEGATIVE', 'True Negative'), ('FALSE_NEGATIVE', 'False Negative'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=32)),
                ('evaluator_confusion_matrix_outcome', models.CharField(choices=[('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('TRUE_NEGATIVE', 'True Negative'), ('FALSE_NEGATIVE', 'False Negative'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=32)),
                ('methods', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry_summary', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_analyses', to='studies.entry')),
            ],
            options={
                'verbose_name': 'Entry Analysis',
                'verbose_name_plural': 'Entry Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='selected_entry_run',
            field=models.ForeignKey(blank=True, help_text='The selected/default analysis for this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studies.entryanalysis'),
        ),
        migrations.CreateModel(
            name='EntryAnalysisIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entry_issues', to=settings.AUTH_USER_MODEL)),
                ('entry_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignments', to='studies.entryanalysis')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_analysis_assignments', to='studies.canonicalissue')),
            ],
            options={
                'verbose_name': 'Entry Analysis Canonical Issue',
                'verbose_name_plural': 'Entry Analysis Canonical Issues',
                'ordering': ['issue__name'],
            },
        ),
        migrations.AddField(
            model_name='entryanalysis',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='entry_analyses', through='studies.EntryAnalysisIssue', to='studies.canonicalissue'),
        ),
        migrations.CreateModel(
            name='EntryAnalysisTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entry_themes', to=settings.AUTH_USER_MODEL)),
                ('entry_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_assignments', to='studies.entryanalysis')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_analysis_assignments', to='studies.canonicaltheme')),
            ],
            options={
                'verbose_name': 'Entry Analysis Canonical Theme',
                'verbose_name_plural': 'Entry Analysis Canonical Themes',
                'ordering': ['theme__name'],
            },
        ),
        migrations.AddField(
            model_name='entryanalysis',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='entry_analyses', through='studies.EntryAnalysisTheme', to='studies.canonicaltheme'),
        ),
        migrations.CreateModel(
            name='EntryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('evaluator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_evaluations', to='studies.entry')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry Evaluation',
                'verbose_name_plural': 'Entry Evaluations',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryEvaluationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluator_entry_evaluation_issues', to=settings.AUTH_USER_MODEL)),
                ('entry_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_issue_assignments', to='studies.entryevaluation')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_evaluation_assignments', to='studies.canonicalissue')),
            ],
            options={
                'verbose_name': 'Entry Evaluation Issue',
                'verbose_name_plural': 'Entry Evaluation Issues',
                'ordering': ['issue__name'],
            },
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='evaluator_issues',
            field=models.ManyToManyField(blank=True, related_name='entry_evaluations', through='studies.EntryEvaluationIssue', to='studies.canonicalissue'),
        ),
        migrations.CreateModel(
            name='EntryEvaluationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluator_entry_evaluation_themes', to=settings.AUTH_USER_MODEL)),
                ('entry_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_theme_assignments', to='studies.entryevaluation')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_evaluation_assignments', to='studies.canonicaltheme')),
            ],
            options={
                'verbose_name': 'Entry Evaluation Theme',
                'verbose_name_plural': 'Entry Evaluation Themes',
                'ordering': ['theme__name'],
            },
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='evaluator_themes',
            field=models.ManyToManyField(blank=True, related_name='entry_evaluations', through='studies.EntryEvaluationTheme', to='studies.canonicaltheme'),
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likert_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_responses', to='studies.entry')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='studies.prompt')),
            ],
            options={
                'verbose_name': 'Prompt Response',
                'verbose_name_plural': 'Prompt Responses',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('hypotheses', models.TextField(blank=True)),
                ('participant_instructions', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('COLLECTING', 'Collecting entries'), ('ANALYZING', 'Analyzing study'), ('MACHINE_ANALYSIS', 'Machine analyzing study'), ('HUMAN_ANALYSIS', 'Pending human analysis'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20)),
                ('data_collection_start', models.DateTimeField(blank=True, null=True)),
                ('data_collection_end', models.DateTimeField(blank=True, null=True)),
                ('entry_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('EVENT_BASED', 'Event-based'), ('FREEFORM', 'Freeform')], default='DAILY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_average_sentiment_score', models.FloatField(blank=True, null=True)),
                ('evaluated_average_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('evaluated_dominant_sentiment_score', models.FloatField(blank=True, null=True)),
                ('evaluated_dominant_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='studies.study'),
        ),
        migrations.AddField(
            model_name='entry',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='studies.study'),
        ),
        migrations.CreateModel(
            name='StudyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('analysis_model', models.CharField(max_length=100)),
                ('analysis_version', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('average_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('average_sentiment_score', models.FloatField(blank=True, null=True)),
                ('dominant_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('dominant_sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_distribution', models.JSONField(blank=True, default=dict)),
                ('evolution_over_time', models.JSONField(blank=True, default=list)),
                ('top_representative_quotes', models.JSONField(blank=True, default=list)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('total_themes', models.PositiveIntegerField(default=0)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('methods', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('participant_average_sentiment_score', models.FloatField(blank=True, null=True)),
                ('participant_average_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('participant_dominant_sentiment_score', models.FloatField(blank=True, null=True)),
                ('participant_dominant_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('participant_abs_distance_average_sentiment', models.IntegerField(blank=True, null=True)),
                ('participant_abs_distance_dominant_sentiment', models.IntegerField(blank=True, null=True)),
                ('participant_sentiment_distribution', models.JSONField(blank=True, default=dict)),
                ('participant_sentiment_true_positives', models.PositiveIntegerField(default=0)),
                ('participant_sentiment_false_positives', models.PositiveIntegerField(default=0)),
                ('participant_sentiment_true_negatives', models.PositiveIntegerField(default=0)),
                ('participant_sentiment_false_negatives', models.PositiveIntegerField(default=0)),
                ('run_accuracy_v_participant', models.FloatField(blank=True, null=True)),
                ('run_precision_v_participant', models.FloatField(blank=True, null=True)),
                ('run_recall_v_participant', models.FloatField(blank=True, null=True)),
                ('run_f1_v_participant', models.FloatField(blank=True, null=True)),
                ('participant_sentiment_metrics_by_category', models.JSONField(blank=True, default=dict, help_text='One-vs-rest TP, FP, TN, FN, accuracy, precision, recall, and F1 per sentiment category against participant self-reported sentiment.')),
                ('evaluator_average_sentiment_score', models.FloatField(blank=True, null=True)),
                ('evaluator_average_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('evaluator_dominant_sentiment_score', models.FloatField(blank=True, null=True)),
                ('evaluator_dominant_sentiment_label', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True)),
                ('evaluator_abs_distance_average_sentiment', models.IntegerField(blank=True, null=True)),
                ('evaluator_abs_distance_dominant_sentiment', models.IntegerField(blank=True, null=True)),
                ('evaluator_sentiment_distribution', models.JSONField(blank=True, default=dict)),
                ('evaluator_sentiment_true_positives', models.PositiveIntegerField(default=0)),
                ('evaluator_sentiment_false_positives', models.PositiveIntegerField(default=0)),
                ('evaluator_sentiment_true_negatives', models.PositiveIntegerField(default=0)),
                ('evaluator_sentiment_false_negatives', models.PositiveIntegerField(default=0)),
                ('run_accuracy_v_evaluator', models.FloatField(blank=True, null=True)),
                ('run_precision_v_evaluator', models.FloatField(blank=True, null=True)),
                ('run_recall_v_evaluator', models.FloatField(blank=True, null=True)),
                ('run_f1_v_evaluator', models.FloatField(blank=True, null=True)),
                ('evaluator_sentiment_metrics_by_category', models.JSONField(blank=True, default=dict, help_text='One-vs-rest TP, FP, TN, FN, accuracy, precision, recall, and F1 per sentiment category against evaluator-reviewed sentiment.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this analysis run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runs', to=settings.AUTH_USER_MODEL)),
                ('dominant_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_in_analysis_runs', to='studies.canonicaltheme')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='studies.study')),
            ],
            options={
                'verbose_name': 'Study Analysis Run',
                'verbose_name_plural': 'Study Analysis Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='study',
            name='selected_study_run',
            field=models.ForeignKey(blank=True, help_text='The analysis run selected as the preferred interpretation for this study.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_studies', to='studies.studyanalysis'),
        ),
        migrations.AddField(
            model_name='entryanalysis',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_analyses', to='studies.studyanalysis'),
        ),
        migrations.CreateModel(
            name='StudyAnalysisIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('average_confidence_score', models.FloatField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_summaries', to='studies.canonicalissue')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_summaries', to='studies.studyanalysis')),
            ],
            options={
                'verbose_name': 'Study Analysis Run Canonical Issue',
                'verbose_name_plural': 'Study Analysis Run Canonical Issues',
                'ordering': ['-entry_count', 'issue__name'],
            },
        ),
        migrations.AddField(
            model_name='studyanalysis',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='analysis_runs', through='studies.StudyAnalysisIssue', to='studies.canonicalissue'),
        ),
        migrations.CreateModel(
            name='StudyAnalysisTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('average_confidence_score', models.FloatField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_summaries', to='studies.studyanalysis')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_summaries', to='studies.canonicaltheme')),
            ],
            options={
                'verbose_name': 'Study Analysis Run Canonical Theme',
                'verbose_name_plural': 'Study Analysis Run Canonical Themes',
                'ordering': ['-entry_count', 'theme__name'],
            },
        ),
        migrations.AddField(
            model_name='studyanalysis',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='analysis_runs', through='studies.StudyAnalysisTheme', to='studies.canonicaltheme'),
        ),
        migrations.CreateModel(
            name='StudyEvaluationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('average_confidence_score', models.FloatField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_evaluation_summaries', to='studies.canonicalissue')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_issue_summaries', to='studies.study')),
            ],
            options={
                'verbose_name': 'Study Evaluation Issue',
                'verbose_name_plural': 'Study Evaluation Issues',
                'ordering': ['-entry_count', 'issue__name'],
            },
        ),
        migrations.AddField(
            model_name='study',
            name='evaluated_issues',
            field=models.ManyToManyField(blank=True, related_name='issue_evaluated_studies', through='studies.StudyEvaluationIssue', to='studies.canonicalissue'),
        ),
        migrations.CreateModel(
            name='StudyEvaluationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('average_confidence_score', models.FloatField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_theme_summaries', to='studies.study')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_evaluation_summaries', to='studies.canonicaltheme')),
            ],
            options={
                'verbose_name': 'Study Evaluation Theme',
                'verbose_name_plural': 'Study Evaluation Themes',
                'ordering': ['-entry_count', 'theme__name'],
            },
        ),
        migrations.AddField(
            model_name='study',
            name='evaluated_themes',
            field=models.ManyToManyField(blank=True, related_name='theme_evaluated_studies', through='studies.StudyEvaluationTheme', to='studies.canonicaltheme'),
        ),
        migrations.CreateModel(
            name='StudyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EVALUATOR', 'Evaluator'), ('PARTICIPANT', 'Participant')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studies.study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Membership',
                'verbose_name_plural': 'Study Memberships',
            },
        ),
        migrations.CreateModel(
            name='UXFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('framework_type', models.CharField(choices=[('NIELSEN', 'Nielsen'), ('ISO', 'ISO'), ('WCAG', 'WCAG'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Source, publication, standard, or reference used for this framework.', max_length=255)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ux_frameworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UX Framework',
                'verbose_name_plural': 'UX Frameworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UXFrameworkCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Optional framework code, e.g. N1, ISO-9241-EFFICIENCY.', max_length=80)),
                ('name', models.CharField(help_text='Name of the framework criterion, heuristic, principle, dimension, or guideline, e.g. Visibility of System Status or Efficiency.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Explain what this criterion means and what kind of usability problem it helps identify.')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative terms, labels, or phrases that may refer to this criterion. Used to support matching and search.')),
                ('examples', models.TextField(blank=True, help_text='Optional examples of user comments, diary evidence, or UX situations that would fit this criterion.')),
                ('recommendation_guidance', models.TextField(blank=True, help_text='Reusable recommendation guidance associated with this framework criterion.')),
                ('evaluation_questions', models.JSONField(blank=True, default=list, help_text='Optional evaluator-facing questions that help interpret this criterion.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='studies.uxframework')),
            ],
            options={
                'verbose_name': 'UX Framework Criterion',
                'verbose_name_plural': 'UX Framework Criteria',
                'ordering': ['framework__name', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalThemeToFrameworkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('TFIDF', 'TF-IDF similarity'), ('EMBEDDING', 'Embedding similarity')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Similarity or confidence score produced by the matching method.', null=True)),
                ('rationale', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_theme_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_theme_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='studies.canonicaltheme')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_mappings', to='studies.uxframeworkcriterion')),
            ],
            options={
                'verbose_name': 'Canonical Theme to Framework Mapping',
                'verbose_name_plural': 'Canonical Theme to Framework Mappings',
                'ordering': ['theme__name', 'criterion__framework__name', 'criterion__name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalIssueToFrameworkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('TFIDF', 'TF-IDF similarity'), ('EMBEDDING', 'Embedding similarity')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Similarity or confidence score produced by the matching method.', null=True)),
                ('rationale', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issue_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issue_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='studies.canonicalissue')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_mappings', to='studies.uxframeworkcriterion')),
            ],
            options={
                'verbose_name': 'Canonical Issue to Framework Mapping',
                'verbose_name_plural': 'Canonical Issue to Framework Mappings',
                'ordering': ['issue__name', 'criterion__framework__name', 'criterion__name'],
            },
        ),
        migrations.AddIndex(
            model_name='canonicalissue',
            index=models.Index(fields=['is_active'], name='studies_can_is_acti_b87cce_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissue',
            index=models.Index(fields=['name'], name='studies_can_name_614517_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaltheme',
            index=models.Index(fields=['is_active'], name='studies_can_is_acti_205274_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaltheme',
            index=models.Index(fields=['name'], name='studies_can_name_e99c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='entryanalysisissue',
            index=models.Index(fields=['entry_analysis'], name='studies_ent_entry_a_2dd052_idx'),
        ),
        migrations.AddIndex(
            model_name='entryanalysisissue',
            index=models.Index(fields=['issue'], name='studies_ent_issue_i_83913e_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryanalysisissue',
            constraint=models.UniqueConstraint(fields=('entry_analysis', 'issue'), name='unique_issue_per_entry_analysis'),
        ),
        migrations.AddIndex(
            model_name='entryanalysistheme',
            index=models.Index(fields=['entry_analysis'], name='studies_ent_entry_a_b5071d_idx'),
        ),
        migrations.AddIndex(
            model_name='entryanalysistheme',
            index=models.Index(fields=['theme'], name='studies_ent_theme_i_5f66f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryanalysistheme',
            constraint=models.UniqueConstraint(fields=('entry_analysis', 'theme'), name='unique_theme_per_entry_analysis'),
        ),
        migrations.AddIndex(
            model_name='entryevaluationissue',
            index=models.Index(fields=['entry_evaluation'], name='studies_ent_entry_e_db0695_idx'),
        ),
        migrations.AddIndex(
            model_name='entryevaluationissue',
            index=models.Index(fields=['issue'], name='studies_ent_issue_i_aca780_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryevaluationissue',
            constraint=models.UniqueConstraint(fields=('entry_evaluation', 'issue'), name='unique_evaluator_issue_per_entry_evaluation'),
        ),
        migrations.AddIndex(
            model_name='entryevaluationtheme',
            index=models.Index(fields=['entry_evaluation'], name='studies_ent_entry_e_67d83f_idx'),
        ),
        migrations.AddIndex(
            model_name='entryevaluationtheme',
            index=models.Index(fields=['theme'], name='studies_ent_theme_i_45f40e_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryevaluationtheme',
            constraint=models.UniqueConstraint(fields=('entry_evaluation', 'theme'), name='unique_evaluator_theme_per_entry_evaluation'),
        ),
        migrations.AddIndex(
            model_name='entryevaluation',
            index=models.Index(fields=['entry'], name='studies_ent_entry_i_66bfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='entryevaluation',
            index=models.Index(fields=['evaluated_by'], name='studies_ent_evaluat_20c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='entryevaluation',
            index=models.Index(fields=['updated_at'], name='studies_ent_updated_0590ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryevaluation',
            constraint=models.UniqueConstraint(fields=('entry', 'evaluated_by'), name='unique_entry_evaluation_per_evaluator'),
        ),
        migrations.AddConstraint(
            model_name='promptresponse',
            constraint=models.UniqueConstraint(fields=('entry', 'prompt'), name='unique_prompt_per_entry'),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='prompt_order_gte_1'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['study', 'participant', 'created_at'], name='studies_ent_study_i_271a75_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['study', 'participant_external_id', 'created_at'], name='studies_ent_study_i_2ba8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='entryanalysis',
            index=models.Index(fields=['run'], name='studies_ent_run_id_fcbab3_idx'),
        ),
        migrations.AddIndex(
            model_name='entryanalysis',
            index=models.Index(fields=['entry'], name='studies_ent_entry_i_51c587_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryanalysis',
            constraint=models.UniqueConstraint(fields=('run', 'entry'), name='unique_entry_per_run_analysis'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisissue',
            index=models.Index(fields=['run'], name='studies_stu_run_id_8f8b58_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisissue',
            index=models.Index(fields=['issue'], name='studies_stu_issue_i_bacb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisissue',
            index=models.Index(fields=['run', 'entry_count'], name='studies_stu_run_id_318252_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyanalysisissue',
            constraint=models.UniqueConstraint(fields=('run', 'issue'), name='unique_issue_per_run'),
        ),
        migrations.AddIndex(
            model_name='studyanalysistheme',
            index=models.Index(fields=['run'], name='studies_stu_run_id_f61e73_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysistheme',
            index=models.Index(fields=['theme'], name='studies_stu_theme_i_36867f_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysistheme',
            index=models.Index(fields=['run', 'entry_count'], name='studies_stu_run_id_3a40c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyanalysistheme',
            constraint=models.UniqueConstraint(fields=('run', 'theme'), name='unique_theme_per_run'),
        ),
        migrations.AddIndex(
            model_name='studyevaluationissue',
            index=models.Index(fields=['study'], name='studies_stu_study_i_c67fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevaluationissue',
            index=models.Index(fields=['issue'], name='studies_stu_issue_i_1037e2_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevaluationissue',
            index=models.Index(fields=['study', 'entry_count'], name='studies_stu_study_i_a9d734_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyevaluationissue',
            constraint=models.UniqueConstraint(fields=('study', 'issue'), name='unique_issue_per_study'),
        ),
        migrations.AddIndex(
            model_name='studyevaluationtheme',
            index=models.Index(fields=['study'], name='studies_stu_study_i_225b82_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevaluationtheme',
            index=models.Index(fields=['theme'], name='studies_stu_theme_i_4addb4_idx'),
        ),
        migrations.AddIndex(
            model_name='studyevaluationtheme',
            index=models.Index(fields=['study', 'entry_count'], name='studies_stu_study_i_d62320_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyevaluationtheme',
            constraint=models.UniqueConstraint(fields=('study', 'theme'), name='unique_theme_per_study'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['user', 'role'], name='studies_stu_user_id_548371_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['study', 'role'], name='studies_stu_study_i_1fe7cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='studymembership',
            constraint=models.UniqueConstraint(fields=('study', 'user'), name='unique_user_per_study'),
        ),
        migrations.AddIndex(
            model_name='uxframework',
            index=models.Index(fields=['is_active'], name='studies_uxf_is_acti_1caa42_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframework',
            index=models.Index(fields=['framework_type'], name='studies_uxf_framewo_ebc2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframework',
            index=models.Index(fields=['name'], name='studies_uxf_name_4db0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframeworkcriterion',
            index=models.Index(fields=['framework'], name='studies_uxf_framewo_2d973a_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframeworkcriterion',
            index=models.Index(fields=['is_active'], name='studies_uxf_is_acti_1cec7e_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframeworkcriterion',
            index=models.Index(fields=['name'], name='studies_uxf_name_949bfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='uxframeworkcriterion',
            constraint=models.UniqueConstraint(fields=('framework', 'name'), name='unique_ux_framework_criterion_name'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['theme'], name='studies_can_theme_i_910b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['criterion'], name='studies_can_criteri_f34d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['method'], name='studies_can_method_10c78f_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['status'], name='studies_can_status_51e634_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalthemetoframeworkmapping',
            constraint=models.UniqueConstraint(fields=('theme', 'criterion'), name='unique_theme_to_framework_criterion'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['issue'], name='studies_can_issue_i_fffd35_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['criterion'], name='studies_can_criteri_dcdf99_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['method'], name='studies_can_method_dd0f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['status'], name='studies_can_status_f96c29_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalissuetoframeworkmapping',
            constraint=models.UniqueConstraint(fields=('issue', 'criterion'), name='unique_issue_to_framework_criterion'),
        ),
    ]
