# Generated by Django 6.0.2 on 2026-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryanalysisissue',
            options={'ordering': ['issue__name'], 'verbose_name': 'Entry Analysis Issue', 'verbose_name_plural': 'Entry Analysis Issues'},
        ),
        migrations.AlterModelOptions(
            name='entryanalysistheme',
            options={'ordering': ['theme__name'], 'verbose_name': 'Entry Analysis Theme', 'verbose_name_plural': 'Entry Analysis Themes'},
        ),
        migrations.AlterModelOptions(
            name='studyanalysis',
            options={'ordering': ['-started_at'], 'verbose_name': 'Study Analysis', 'verbose_name_plural': 'Study Analyses'},
        ),
        migrations.AlterModelOptions(
            name='studyanalysisissue',
            options={'ordering': ['-entry_count', 'issue__name'], 'verbose_name': 'Study Analysis Issue', 'verbose_name_plural': 'Study Analysis Issues'},
        ),
        migrations.AlterModelOptions(
            name='studyanalysistheme',
            options={'ordering': ['-entry_count', 'theme__name'], 'verbose_name': 'Study Analysis Theme', 'verbose_name_plural': 'Study Analysis Themes'},
        ),
        migrations.RemoveField(
            model_name='entryanalysisissue',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='entryanalysistheme',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='entryanalysisissue',
            name='assigned_by_method',
            field=models.CharField(blank=True, help_text='NLP technique, LLM provider/model, or process that assigned this issue.', max_length=100),
        ),
        migrations.AddField(
            model_name='entryanalysistheme',
            name='assigned_by_method',
            field=models.CharField(blank=True, help_text='Name of the NLP technique, LLM provider/model, or process that assigned this theme.', max_length=100),
        ),
    ]
