# Generated by Django 6.0.2 on 2026-03-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='objective',
            new_name='goal',
        ),
        migrations.AddField(
            model_name='study',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
