# Generated by Django 6.0.2 on 2026-03-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_rename_objective_study_goal_study_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='instructions',
        ),
    ]
