# Generated by Django 6.0.2 on 2026-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_entryanalysisissue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisissue',
            name='average_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysistheme',
            name='average_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
