# Generated by Django 6.0.2 on 2026-06-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_studyanalysisissue_average_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='participant_reported_average_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='participant_reported_average_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='participant_reported_dominant_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='participant_reported_dominant_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
