# Generated by Django 6.0.2 on 2026-03-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_remove_study_instructions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diaryentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Diary Entry",
                "verbose_name_plural": "Diary Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="promptresponse",
            options={
                "verbose_name": "Prompt Response",
                "verbose_name_plural": "Prompt Responses",
            },
        ),
        migrations.AlterModelOptions(
            name="study",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Study",
                "verbose_name_plural": "Studies",
            },
        ),
        migrations.AlterModelOptions(
            name="studymembership",
            options={
                "verbose_name": "Study Membership",
                "verbose_name_plural": "Study Memberships",
            },
        ),
    ]
