# Generated by Django 6.0.2 on 2026-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_diaryentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='issue_encountered',
            field=models.BooleanField(default=False, help_text='Did you encounter any issue or friction during this experience?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='sentiment_self_report',
            field=models.CharField(choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], default=False, help_text='How would you describe your overall experience sentiment for this entry?', max_length=20),
            preserve_default=False,
        ),
    ]
