# Generated by Django 6.0.2 on 2026-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_study_participant_reported_average_sentiment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='participant_sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
