# Generated by Django 6.0.2 on 2026-06-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_study_participant_sentiment_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='evaluated_sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
