# Generated by Django 6.0.2 on 2026-03-27 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0005_diaryentry_issue_encountered_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="participant_display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="participant_external_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "ChronicleUX submission"),
                    ("EXTERNAL", "External submission imported into ChronicleUX"),
                ],
                default="INTERNAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diary_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(
                fields=["study", "participant_external_id", "created_at"],
                name="studies_dia_study_i_12252d_idx",
            ),
        ),
    ]
