# Generated by Django 6.0.2 on 2026-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_diaryentry_participant_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='participant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
