# Generated by Django 6.0.2 on 2026-06-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_study_evaluated_sentiment_distribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='evaluated_average_sentiment_label',
            new_name='evaluator_average_sentiment_label',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='evaluated_average_sentiment_score',
            new_name='evaluator_average_sentiment_score',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='evaluated_dominant_sentiment_label',
            new_name='evaluator_dominant_sentiment_label',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='evaluated_dominant_sentiment_score',
            new_name='evaluator_dominant_sentiment_score',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='evaluated_sentiment_distribution',
            new_name='evaluator_sentiment_distribution',
        ),
    ]
