# Generated by Django 6.0.2 on 2026-06-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_rename_evaluated_average_sentiment_label_study_evaluator_average_sentiment_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyanalysis',
            name='evaluator_sentiment_distribution',
        ),
        migrations.RemoveField(
            model_name='studyanalysis',
            name='participant_sentiment_distribution',
        ),
    ]
