# Generated by Django 6.0.2 on 2026-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_study_sentiment_study_sentiment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='sentiment_category',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
    ]
