# Generated by Django 6.0.2 on 2026-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_remove_studyanalysis_evaluator_sentiment_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysis',
            name='evaluator_sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyanalysis',
            name='participant_sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
