# Generated by Django 6.0.2 on 2026-06-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_studyanalysis_evaluator_sentiment_distribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='evaluated_issues',
        ),
        migrations.RemoveField(
            model_name='study',
            name='evaluated_themes',
        ),
        migrations.AddField(
            model_name='study',
            name='evaluator_issues',
            field=models.ManyToManyField(blank=True, related_name='evaluated_in_studies', through='studies.StudyEvaluationIssue', to='studies.canonicalissue'),
        ),
        migrations.AddField(
            model_name='study',
            name='evaluator_themes',
            field=models.ManyToManyField(blank=True, related_name='evaluated_in_studies', through='studies.StudyEvaluationTheme', to='studies.canonicaltheme'),
        ),
        migrations.AlterField(
            model_name='studyevaluationissue',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_issue_summaries', to='studies.study'),
        ),
        migrations.AlterField(
            model_name='studyevaluationtheme',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_theme_summaries', to='studies.study'),
        ),
    ]
