# Generated by Django 6.0.2 on 2026-04-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_diaryentry_sentiment_diaryentry_sentiment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='sentiment',
            new_name='avg_sentiment',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_issue_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_issue_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='entry_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='analysis_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='analysis_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='study',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='evolution_over_time',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='study',
            name='recurring_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='study',
            name='recurring_themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='study',
            name='sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='study',
            name='top_representative_quotes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StudyAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_model', models.CharField(max_length=100)),
                ('analysis_version', models.CharField(max_length=50)),
                ('sentiment_distribution', models.JSONField(blank=True, default=dict)),
                ('recurring_issues', models.JSONField(blank=True, default=list)),
                ('recurring_themes', models.JSONField(blank=True, default=list)),
                ('evolution_over_time', models.JSONField(blank=True, default=list)),
                ('top_representative_quotes', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='studies.study')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('sentiment_category', models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True)),
                ('issue_detected', models.BooleanField(default=False)),
                ('issue_tags', models.JSONField(blank=True, default=list)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('entry_summary', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='studies.diaryentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_analyses', to='studies.studyanalysisrun')),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['run'], name='studies_dia_run_id_83b278_idx'), models.Index(fields=['entry'], name='studies_dia_entry_i_a3732a_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'entry'), name='unique_entry_per_run_analysis')],
            },
        ),
    ]
