# Generated by Django 6.0.2 on 2026-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_rename_sentiment_study_avg_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('COLLECTING', 'Collecting diary entries'), ('MACHINE_ANALYSIS', 'Machine analyzing diary entries'), ('HUMAN_ANALYSIS', 'Human analyzing results'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20),
        ),
    ]
