# Generated by Django 6.0.2 on 2026-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_remove_study_evaluated_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysis',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw result of study analysis'),
        ),
    ]
