# Generated by Django 6.0.2 on 2026-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_alter_study_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('COLLECTING', 'Collecting diary entries'), ('MACHINE_ANALYSIS', 'Machine analyzing study'), ('HUMAN_ANALYSIS', 'Pending human analysis'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20),
        ),
    ]
