# Generated by Django 6.0.2 on 2026-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_alter_study_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='avg_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='sentiment_category',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='analysis_model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='study',
            name='analysis_version',
            field=models.CharField(max_length=50),
        ),
    ]
