# Generated by Django 6.0.2 on 2026-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_studyanalysisrun_avg_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentryanalysis',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'Diary Entry Analysis', 'verbose_name_plural': 'Diary Entry Analyses'},
        ),
        migrations.AlterModelOptions(
            name='studyanalysisrun',
            options={'ordering': ['-started_at'], 'verbose_name': 'Study Analysis Run', 'verbose_name_plural': 'Study Analysis Runs'},
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='average_study_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='average_study_theme_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='dominant_study_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='dominant_study_theme_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='entry_analysis_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='methods',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='study_sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='study_theme_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='total_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='total_themes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
