# Generated by Django 6.0.2 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_alter_diaryentryanalysis_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentryanalysis',
            old_name='issue_tags',
            new_name='issues',
        ),
        migrations.RenameField(
            model_name='diaryentryanalysis',
            old_name='themes',
            new_name='raw_sentiment_result',
        ),
        migrations.RenameField(
            model_name='diaryentryanalysis',
            old_name='sentiment_category',
            new_name='sentiment_label',
        ),
        migrations.RenameField(
            model_name='diaryentryanalysis',
            old_name='sentiment',
            new_name='sentiment_score',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='average_study_sentiment_score',
            new_name='average_sentiment_score',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='average_study_theme_weight',
            new_name='average_theme_weight',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='recurring_themes',
            new_name='dominant_sentiment_evolution_over_time',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='dominant_study_sentiment_label',
            new_name='dominant_sentiment_label',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='dominant_study_theme_label',
            new_name='dominant_theme_label',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='study_sentiment_distribution',
            new_name='issue_distribution',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='study_theme_distribution',
            new_name='theme_distribution',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='avg_sentiment',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='sentiment_category',
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='methods',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='raw_theme_result',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='theme_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='theme_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='dominant_study_theme_evolution_over_time',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='issue_distribution_over_time',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
