# Generated by Django 6.0.2 on 2026-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0015_rename_issue_tags_diaryentryanalysis_issues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='sentiment_category',
            new_name='machine_sentiment_label',
        ),
        migrations.RenameField(
            model_name='diaryentry',
            old_name='sentiment',
            new_name='machine_sentiment_score',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='average_theme_weight',
            new_name='dominant_sentiment_score',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='dominant_study_theme_evolution_over_time',
            new_name='dominant_theme_evolution_over_time',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='analysis_themes',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='machine_theme_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='machine_theme_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='average_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='dominant_theme_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='recurring_themes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
