# Generated by Django 6.0.2 on 2026-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_rename_sentiment_category_diaryentry_machine_sentiment_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='sentiment_category',
            new_name='average_sentiment_label',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='avg_sentiment',
            new_name='average_sentiment_score',
        ),
        migrations.RemoveField(
            model_name='study',
            name='recurring_themes',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='dominant_sentiment_evolution_over_time',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='dominant_theme_evolution_over_time',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='issue_distribution',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='issue_distribution_over_time',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='recurring_themes',
        ),
        migrations.AddField(
            model_name='study',
            name='dominant_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='dominant_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='dominant_theme_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='dominant_theme_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='theme_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='study',
            name='total_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='total_themes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
