# Generated by Django 6.0.2 on 2026-05-30 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_rename_sentiment_category_study_average_sentiment_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='evaluators',
            field=models.ManyToManyField(blank=True, related_name='evaluating_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
