# Generated by Django 6.0.2 on 2026-05-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_study_evaluators_study_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='evaluators',
        ),
        migrations.RemoveField(
            model_name='study',
            name='participants',
        ),
    ]
