# Generated by Django 6.0.2 on 2026-06-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0019_remove_study_evaluators_remove_study_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='analysis_issue_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
