# Generated by Django 6.0.2 on 2026-06-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0020_alter_diaryentry_analysis_issue_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='analysis_model',
        ),
        migrations.RemoveField(
            model_name='study',
            name='analysis_version',
        ),
        migrations.RemoveField(
            model_name='study',
            name='analyzed_at',
        ),
        migrations.RemoveField(
            model_name='study',
            name='average_sentiment_label',
        ),
        migrations.RemoveField(
            model_name='study',
            name='average_sentiment_score',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dominant_sentiment_label',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dominant_sentiment_score',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dominant_theme_label',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dominant_theme_weight',
        ),
        migrations.RemoveField(
            model_name='study',
            name='evolution_over_time',
        ),
        migrations.RemoveField(
            model_name='study',
            name='recurring_issues',
        ),
        migrations.RemoveField(
            model_name='study',
            name='sentiment_distribution',
        ),
        migrations.RemoveField(
            model_name='study',
            name='theme_distribution',
        ),
        migrations.RemoveField(
            model_name='study',
            name='top_representative_quotes',
        ),
        migrations.RemoveField(
            model_name='study',
            name='total_entries',
        ),
        migrations.RemoveField(
            model_name='study',
            name='total_themes',
        ),
        migrations.AddField(
            model_name='study',
            name='selected_run',
            field=models.ForeignKey(blank=True, help_text='The analysis run selected as the preferred interpretation for this study.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_studies', to='studies.studyanalysisrun'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='analysis_issue_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
