# Generated by Django 6.0.2 on 2026-06-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0021_remove_study_analysis_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='analysis_issue_detected',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='analysis_issue_tags',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='analysis_model',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='analysis_version',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='analyzed_at',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='entry_summary',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='machine_sentiment_label',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='machine_sentiment_score',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='machine_theme_label',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='machine_theme_weight',
        ),
    ]
