# Generated by Django 6.0.2 on 2026-06-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0022_remove_diaryentry_analysis_issue_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_issue_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_issue_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analysis_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='entry_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='machine_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='machine_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='machine_theme_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='machine_theme_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
