# Generated by Django 6.0.2 on 2026-06-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0023_diaryentry_analysis_issue_detected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='selected_run',
            new_name='selected_study_run',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='selected_entry_run',
            field=models.ForeignKey(blank=True, help_text='The selected/default analysis for this diary entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studies.diaryentryanalysis'),
        ),
    ]
