# Generated by Django 6.0.2 on 2026-06-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0025_remove_diaryentry_analysis_issue_detected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentryanalysis',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='studies.diaryentry'),
        ),
    ]
