# Generated by Django 6.0.2 on 2026-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0026_alter_diaryentryanalysis_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyanalysisrun',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
    ]
