# Generated by Django 6.0.2 on 2026-06-05 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0027_alter_studyanalysisrun_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this analysis run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
