# Generated by Django 6.0.2 on 2026-06-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0028_studyanalysisrun_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='evaluator_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='participant_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
    ]
