# Generated by Django 6.0.2 on 2026-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0029_diaryentryanalysis_evaluator_sentiment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='evaluator_confusion_matrix_outcome',
            field=models.CharField(choices=[('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('TRUE_NEGATIVE', 'True Negative'), ('FALSE_NEGATIVE', 'False Negative'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=32),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='participant_confusion_matrix_outcome',
            field=models.CharField(choices=[('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('TRUE_NEGATIVE', 'True Negative'), ('FALSE_NEGATIVE', 'False Negative'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=32),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_sentiment_false_negatives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_sentiment_false_positives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_sentiment_true_negatives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_sentiment_true_positives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_sentiment_false_negatives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_sentiment_false_positives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_sentiment_true_negatives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_sentiment_true_positives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_accuracy_v_evaluator',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_accuracy_v_participant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_f1_v_evaluator',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_f1_v_participant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_precision_v_evaluator',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_precision_v_participant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_recall_v_evaluator',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='run_recall_v_participant',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
