# Generated by Django 6.0.2 on 2026-06-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0030_diaryentryanalysis_evaluator_confusion_matrix_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_sentiment_metrics_by_category',
            field=models.JSONField(blank=True, default=dict, help_text='One-vs-rest TP, FP, TN, FN, accuracy, precision, recall, and F1 per sentiment category against evaluator-reviewed sentiment.'),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_sentiment_metrics_by_category',
            field=models.JSONField(blank=True, default=dict, help_text='One-vs-rest TP, FP, TN, FN, accuracy, precision, recall, and F1 per sentiment category against participant self-reported sentiment.'),
        ),
    ]
