# Generated by Django 6.0.2 on 2026-06-10 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0031_studyanalysisrun_evaluator_sentiment_metrics_by_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True, help_text='Optional examples of entries, phrases, or situations that belong to this issue.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canonical_issues', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_issues', to='studies.study')),
            ],
            options={
                'verbose_name': 'Canonical Issue',
                'verbose_name_plural': 'Canonical Issues',
                'ordering': ['study', 'name'],
                'indexes': [models.Index(fields=['study', 'is_active'], name='studies_can_study_i_7dd283_idx'), models.Index(fields=['study', 'name'], name='studies_can_study_i_af262d_idx')],
                'constraints': [models.UniqueConstraint(fields=('study', 'name'), name='unique_canonical_issue_per_study')],
            },
        ),
        migrations.CreateModel(
            name='CanonicalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True, help_text='Optional examples of entries, phrases, or situations that belong to this theme.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canonical_themes', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_themes', to='studies.study')),
            ],
            options={
                'verbose_name': 'Canonical Theme',
                'verbose_name_plural': 'Canonical Themes',
                'ordering': ['study', 'name'],
                'indexes': [models.Index(fields=['study', 'is_active'], name='studies_can_study_i_e68eb7_idx'), models.Index(fields=['study', 'name'], name='studies_can_study_i_ce025a_idx')],
                'constraints': [models.UniqueConstraint(fields=('study', 'name'), name='unique_canonical_theme_per_study')],
            },
        ),
    ]
