# Generated by Django 6.0.2 on 2026-06-10 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0032_canonicalissue_canonicaltheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntryAnalysisCanonicalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diary Entry Analysis Canonical Issue',
                'verbose_name_plural': 'Diary Entry Analysis Canonical Issues',
                'ordering': ['canonical_issue__name'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntryAnalysisCanonicalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diary Entry Analysis Canonical Theme',
                'verbose_name_plural': 'Diary Entry Analysis Canonical Themes',
                'ordering': ['canonical_theme__name'],
            },
        ),
        migrations.CreateModel(
            name='StudyAnalysisRunCanonicalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('average_confidence_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Study Analysis Run Canonical Issue',
                'verbose_name_plural': 'Study Analysis Run Canonical Issues',
                'ordering': ['-entry_count', 'canonical_issue__name'],
            },
        ),
        migrations.CreateModel(
            name='StudyAnalysisRunCanonicalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('average_confidence_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Study Analysis Run Canonical Theme',
                'verbose_name_plural': 'Study Analysis Run Canonical Themes',
                'ordering': ['-entry_count', 'canonical_theme__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='canonicalissue',
            options={'ordering': ['name'], 'verbose_name': 'Canonical Issue', 'verbose_name_plural': 'Canonical Issues'},
        ),
        migrations.AlterModelOptions(
            name='canonicaltheme',
            options={'ordering': ['name'], 'verbose_name': 'Canonical Theme', 'verbose_name_plural': 'Canonical Themes'},
        ),
        migrations.RemoveConstraint(
            model_name='canonicalissue',
            name='unique_canonical_issue_per_study',
        ),
        migrations.RemoveConstraint(
            model_name='canonicaltheme',
            name='unique_canonical_theme_per_study',
        ),
        migrations.RemoveIndex(
            model_name='canonicalissue',
            name='studies_can_study_i_7dd283_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalissue',
            name='studies_can_study_i_af262d_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicaltheme',
            name='studies_can_study_i_e68eb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicaltheme',
            name='studies_can_study_i_ce025a_idx',
        ),
        migrations.AlterField(
            model_name='canonicalissue',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='canonicaltheme',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='canonicalissue',
            index=models.Index(fields=['is_active'], name='studies_can_is_acti_b87cce_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissue',
            index=models.Index(fields=['name'], name='studies_can_name_614517_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaltheme',
            index=models.Index(fields=['is_active'], name='studies_can_is_acti_205274_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaltheme',
            index=models.Index(fields=['name'], name='studies_can_name_e99c9e_idx'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysiscanonicalissue',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entry_canonical_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diaryentryanalysiscanonicalissue',
            name='canonical_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_analysis_assignments', to='studies.canonicalissue'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysiscanonicalissue',
            name='diary_entry_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_issue_assignments', to='studies.diaryentryanalysis'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='canonical_issues',
            field=models.ManyToManyField(blank=True, related_name='diary_entry_analyses', through='studies.DiaryEntryAnalysisCanonicalIssue', to='studies.canonicalissue'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysiscanonicaltheme',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entry_canonical_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diaryentryanalysiscanonicaltheme',
            name='canonical_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_analysis_assignments', to='studies.canonicaltheme'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysiscanonicaltheme',
            name='diary_entry_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_theme_assignments', to='studies.diaryentryanalysis'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='canonical_themes',
            field=models.ManyToManyField(blank=True, related_name='diary_entry_analyses', through='studies.DiaryEntryAnalysisCanonicalTheme', to='studies.canonicaltheme'),
        ),
        migrations.AddField(
            model_name='studyanalysisruncanonicalissue',
            name='canonical_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_summaries', to='studies.canonicalissue'),
        ),
        migrations.AddField(
            model_name='studyanalysisruncanonicalissue',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_issue_summaries', to='studies.studyanalysisrun'),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='canonical_issues',
            field=models.ManyToManyField(blank=True, related_name='analysis_runs', through='studies.StudyAnalysisRunCanonicalIssue', to='studies.canonicalissue'),
        ),
        migrations.AddField(
            model_name='studyanalysisruncanonicaltheme',
            name='canonical_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_summaries', to='studies.canonicaltheme'),
        ),
        migrations.AddField(
            model_name='studyanalysisruncanonicaltheme',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_theme_summaries', to='studies.studyanalysisrun'),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='canonical_themes',
            field=models.ManyToManyField(blank=True, related_name='analysis_runs', through='studies.StudyAnalysisRunCanonicalTheme', to='studies.canonicaltheme'),
        ),
        migrations.RemoveField(
            model_name='canonicalissue',
            name='study',
        ),
        migrations.RemoveField(
            model_name='canonicaltheme',
            name='study',
        ),
        migrations.AddIndex(
            model_name='diaryentryanalysiscanonicalissue',
            index=models.Index(fields=['diary_entry_analysis'], name='studies_dia_diary_e_52b71e_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentryanalysiscanonicalissue',
            index=models.Index(fields=['canonical_issue'], name='studies_dia_canonic_c28361_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaryentryanalysiscanonicalissue',
            constraint=models.UniqueConstraint(fields=('diary_entry_analysis', 'canonical_issue'), name='unique_canonical_issue_per_entry_analysis'),
        ),
        migrations.AddIndex(
            model_name='diaryentryanalysiscanonicaltheme',
            index=models.Index(fields=['diary_entry_analysis'], name='studies_dia_diary_e_6fbdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentryanalysiscanonicaltheme',
            index=models.Index(fields=['canonical_theme'], name='studies_dia_canonic_1b7a4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaryentryanalysiscanonicaltheme',
            constraint=models.UniqueConstraint(fields=('diary_entry_analysis', 'canonical_theme'), name='unique_canonical_theme_per_entry_analysis'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisruncanonicalissue',
            index=models.Index(fields=['run'], name='studies_stu_run_id_516002_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisruncanonicalissue',
            index=models.Index(fields=['canonical_issue'], name='studies_stu_canonic_9dbcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisruncanonicalissue',
            index=models.Index(fields=['run', 'entry_count'], name='studies_stu_run_id_99316a_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyanalysisruncanonicalissue',
            constraint=models.UniqueConstraint(fields=('run', 'canonical_issue'), name='unique_canonical_issue_per_run'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisruncanonicaltheme',
            index=models.Index(fields=['run'], name='studies_stu_run_id_183d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisruncanonicaltheme',
            index=models.Index(fields=['canonical_theme'], name='studies_stu_canonic_3ae0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='studyanalysisruncanonicaltheme',
            index=models.Index(fields=['run', 'entry_count'], name='studies_stu_run_id_c42981_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyanalysisruncanonicaltheme',
            constraint=models.UniqueConstraint(fields=('run', 'canonical_theme'), name='unique_canonical_theme_per_run'),
        ),
    ]
