# Generated by Django 6.0.2 on 2026-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0034_canonicaltheme_aliases_canonicaltheme_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalissue',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='canonicalissue',
            name='source',
            field=models.CharField(blank=True, choices=[('EVALUATOR', 'Evaluator'), ('NLP', 'NLP Model'), ('LLM', 'LLM Model')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='canonicalissue',
            name='status',
            field=models.CharField(blank=True, choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
    ]
