# Generated by Django 6.0.2 on 2026-06-14 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0035_canonicalissue_aliases_canonicalissue_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_entry_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='evaluator_dominant_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator_entry_analyses', to='studies.canonicaltheme'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='evaluator_issues',
            field=models.ManyToManyField(blank=True, related_name='evaluator_entry_analyses', to='studies.canonicalissue'),
        ),
        migrations.AddField(
            model_name='diaryentryanalysis',
            name='evaluator_notes',
            field=models.TextField(blank=True),
        ),
    ]
