# Generated by Django 6.0.2 on 2026-06-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0036_diaryentryanalysis_evaluated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='dominant_theme_label',
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='dominant_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_in_analysis_runs', to='studies.canonicaltheme'),
        ),
    ]
