# Generated by Django 6.0.2 on 2026-06-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0037_remove_studyanalysisrun_dominant_theme_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='dominant_theme_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
