# Generated by Django 6.0.2 on 2026-06-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0038_studyanalysisrun_dominant_theme_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='dominant_theme_label',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='dominant_theme_weight',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='recurring_issues',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='theme_distribution',
        ),
    ]
