# Generated by Django 6.0.2 on 2026-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0039_remove_studyanalysisrun_dominant_theme_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='total_issues',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
