# Generated by Django 6.0.2 on 2026-06-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0040_studyanalysisrun_total_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentryanalysis',
            name='issue_detected',
        ),
        migrations.RemoveField(
            model_name='diaryentryanalysis',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='diaryentryanalysis',
            name='raw_theme_result',
        ),
        migrations.RemoveField(
            model_name='diaryentryanalysis',
            name='theme_label',
        ),
        migrations.RemoveField(
            model_name='diaryentryanalysis',
            name='theme_weight',
        ),
    ]
