# Generated by Django 6.0.2 on 2026-06-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0041_remove_diaryentryanalysis_issue_detected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentryanalysis',
            old_name='canonical_issues',
            new_name='issues',
        ),
        migrations.RenameField(
            model_name='diaryentryanalysis',
            old_name='canonical_themes',
            new_name='themes',
        ),
    ]
