# Generated by Django 6.0.2 on 2026-06-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0042_rename_canonical_issues_diaryentryanalysis_issues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='canonical_issues',
            new_name='issues',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='canonical_themes',
            new_name='themes',
        ),
    ]
