# Generated by Django 6.0.2 on 2026-06-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0043_rename_canonical_issues_studyanalysisrun_issues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='issues',
            new_name='canonical_issues',
        ),
        migrations.RenameField(
            model_name='studyanalysisrun',
            old_name='themes',
            new_name='canonical_themes',
        ),
    ]
