# Generated by Django 6.0.2 on 2026-06-21 15:01 --- Manually updated by Luigi

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0045_rename_canonical_issues_studyanalysisrun_issues_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diaryentryanalysis",
            name="evaluator_issues",
        ),
        # migrations.RemoveField(
        #     model_name="diaryentryanalysis",
        #     name="evaluator_themes",
        # ),
        migrations.RemoveField(
            model_name="diaryentryanalysis",
            name="evaluator_dominant_theme",
        ),

        migrations.CreateModel(
            name="DiaryEntryAnalysisEvaluatorTheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rationale", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_evaluator_entry_themes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canonical_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluator_entry_analysis_assignments",
                        to="studies.canonicaltheme",
                    ),
                ),
                (
                    "diary_entry_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluator_theme_assignments",
                        to="studies.diaryentryanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diary Entry Analysis Evaluator Theme",
                "verbose_name_plural": "Diary Entry Analysis Evaluator Themes",
                "ordering": ["canonical_theme__name"],
            },
        ),

        migrations.CreateModel(
            name="DiaryEntryAnalysisEvaluatorIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rationale", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_evaluator_entry_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canonical_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluator_entry_analysis_assignments",
                        to="studies.canonicalissue",
                    ),
                ),
                (
                    "diary_entry_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluator_issue_assignments",
                        to="studies.diaryentryanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diary Entry Analysis Evaluator Issue",
                "verbose_name_plural": "Diary Entry Analysis Evaluator Issues",
                "ordering": ["canonical_issue__name"],
            },
        ),

        migrations.AddField(
            model_name="diaryentryanalysis",
            name="evaluator_themes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluator_diary_entry_analyses",
                through="studies.DiaryEntryAnalysisEvaluatorTheme",
                to="studies.canonicaltheme",
            ),
        ),

        migrations.AddField(
            model_name="diaryentryanalysis",
            name="evaluator_issues",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluator_diary_entry_analyses",
                through="studies.DiaryEntryAnalysisEvaluatorIssue",
                to="studies.canonicalissue",
            ),
        ),

        migrations.AddConstraint(
            model_name="diaryentryanalysisevaluatortheme",
            constraint=models.UniqueConstraint(
                fields=("diary_entry_analysis", "canonical_theme"),
                name="unique_evaluator_theme_per_entry_analysis",
            ),
        ),

        migrations.AddConstraint(
            model_name="diaryentryanalysisevaluatorissue",
            constraint=models.UniqueConstraint(
                fields=("diary_entry_analysis", "canonical_issue"),
                name="unique_evaluator_issue_per_entry_analysis",
            ),
        ),

        migrations.AddIndex(
            model_name="diaryentryanalysisevaluatortheme",
            index=models.Index(fields=["diary_entry_analysis"], name="studies_dia_diary_e_idx"),
        ),
        migrations.AddIndex(
            model_name="diaryentryanalysisevaluatortheme",
            index=models.Index(fields=["canonical_theme"], name="studies_dia_canonic_idx"),
        ),
        migrations.AddIndex(
            model_name="diaryentryanalysisevaluatorissue",
            index=models.Index(fields=["diary_entry_analysis"], name="studies_dia_diary_ei_idx"),
        ),
        migrations.AddIndex(
            model_name="diaryentryanalysisevaluatorissue",
            index=models.Index(fields=["canonical_issue"], name="studies_dia_canonic_i_idx"),
        ),
    ]
