# Generated by Django 6.0.2 on 2026-06-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0046_remove_diaryentryanalysis_evaluator_dominant_theme_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diaryentryanalysisevaluatorissue',
            new_name='studies_dia_diary_e_7b4c61_idx',
            old_name='studies_dia_diary_ei_idx',
        ),
        migrations.RenameIndex(
            model_name='diaryentryanalysisevaluatorissue',
            new_name='studies_dia_canonic_b70c10_idx',
            old_name='studies_dia_canonic_i_idx',
        ),
        migrations.RenameIndex(
            model_name='diaryentryanalysisevaluatortheme',
            new_name='studies_dia_diary_e_5b8d6d_idx',
            old_name='studies_dia_diary_e_idx',
        ),
        migrations.RenameIndex(
            model_name='diaryentryanalysisevaluatortheme',
            new_name='studies_dia_canonic_313262_idx',
            old_name='studies_dia_canonic_idx',
        ),
        migrations.RemoveField(
            model_name='studyanalysisrun',
            name='entry_analysis_results',
        ),
    ]
