# Generated by Django 6.0.2 on 2026-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0049_remove_studyanalysisrun_entry_analysis_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_abs_distance_average_sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_abs_distance_dominant_sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_average_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_average_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_dominant_sentiment_score',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_abs_distance_average_sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_abs_distance_dominant_sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_average_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_average_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_dominant_sentiment_score',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
    ]
