# Generated by Django 6.0.2 on 2026-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0050_studyanalysisrun_evaluator_abs_distance_average_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_dominant_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_dominant_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studyanalysisrun',
            name='evaluator_dominant_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyanalysisrun',
            name='participant_dominant_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
