# Generated by Django 6.0.2 on 2026-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0051_studyanalysisrun_evaluator_dominant_sentiment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyanalysisrun',
            name='evaluator_sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyanalysisrun',
            name='participant_sentiment_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
