# Generated by Django 6.0.2 on 2026-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0052_studyanalysisrun_evaluator_sentiment_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentryanalysis',
            name='evaluator_sentiment_label',
            field=models.CharField(blank=True, choices=[('VERY_NEGATIVE', 'Very negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very positive'), ('NOT_NEGATIVE', 'Not Negative')], max_length=20, null=True),
        ),
    ]
