# Generated by Django 6.0.2 on 2026-06-24 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0053_alter_diaryentryanalysis_evaluator_sentiment_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('COLLECTING', 'Collecting diary entries'), ('ANALYZING', 'Analyzing study'), ('MACHINE_ANALYSIS', 'Machine analyzing study'), ('HUMAN_ANALYSIS', 'Pending human analysis'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20),
        ),
        migrations.CreateModel(
            name='UXFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('framework_type', models.CharField(choices=[('NIELSEN', 'Nielsen'), ('ISO', 'ISO'), ('WCAG', 'WCAG'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Source, publication, standard, or reference used for this framework.', max_length=255)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ux_frameworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UX Framework',
                'verbose_name_plural': 'UX Frameworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UXFrameworkCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Optional framework code or ordering label, e.g. N1, ISO-9241-EFFICIENCY.', max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('examples', models.TextField(blank=True)),
                ('recommendation_guidance', models.TextField(blank=True, help_text='Reusable recommendation guidance associated with this framework criterion.')),
                ('evaluation_questions', models.JSONField(blank=True, default=list, help_text='Optional evaluator-facing questions that help interpret this criterion.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='studies.uxframework')),
            ],
            options={
                'verbose_name': 'UX Framework Criterion',
                'verbose_name_plural': 'UX Framework Criteria',
                'ordering': ['framework__name', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalThemeToFrameworkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('TFIDF', 'TF-IDF similarity'), ('EMBEDDING', 'Embedding similarity')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Similarity or confidence score produced by the matching method.', null=True)),
                ('rationale', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_theme_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('canonical_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='studies.canonicaltheme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_theme_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_mappings', to='studies.uxframeworkcriterion')),
            ],
            options={
                'verbose_name': 'Canonical Theme to Framework Mapping',
                'verbose_name_plural': 'Canonical Theme to Framework Mappings',
                'ordering': ['canonical_theme__name', 'criterion__framework__name', 'criterion__name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalIssueToFrameworkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('TFIDF', 'TF-IDF similarity'), ('EMBEDDING', 'Embedding similarity')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Similarity or confidence score produced by the matching method.', null=True)),
                ('rationale', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issue_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('canonical_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='studies.canonicalissue')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issue_framework_mappings', to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_mappings', to='studies.uxframeworkcriterion')),
            ],
            options={
                'verbose_name': 'Canonical Issue to Framework Mapping',
                'verbose_name_plural': 'Canonical Issue to Framework Mappings',
                'ordering': ['canonical_issue__name', 'criterion__framework__name', 'criterion__name'],
            },
        ),
        migrations.AddIndex(
            model_name='uxframework',
            index=models.Index(fields=['is_active'], name='studies_uxf_is_acti_1caa42_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframework',
            index=models.Index(fields=['framework_type'], name='studies_uxf_framewo_ebc2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframework',
            index=models.Index(fields=['name'], name='studies_uxf_name_4db0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframeworkcriterion',
            index=models.Index(fields=['framework'], name='studies_uxf_framewo_2d973a_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframeworkcriterion',
            index=models.Index(fields=['is_active'], name='studies_uxf_is_acti_1cec7e_idx'),
        ),
        migrations.AddIndex(
            model_name='uxframeworkcriterion',
            index=models.Index(fields=['name'], name='studies_uxf_name_949bfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='uxframeworkcriterion',
            constraint=models.UniqueConstraint(fields=('framework', 'name'), name='unique_ux_framework_criterion_name'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['canonical_theme'], name='studies_can_canonic_bb4dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['criterion'], name='studies_can_criteri_f34d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['method'], name='studies_can_method_10c78f_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalthemetoframeworkmapping',
            index=models.Index(fields=['status'], name='studies_can_status_51e634_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalthemetoframeworkmapping',
            constraint=models.UniqueConstraint(fields=('canonical_theme', 'criterion'), name='unique_theme_to_framework_criterion'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['canonical_issue'], name='studies_can_canonic_0e3c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['criterion'], name='studies_can_criteri_dcdf99_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['method'], name='studies_can_method_dd0f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalissuetoframeworkmapping',
            index=models.Index(fields=['status'], name='studies_can_status_f96c29_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalissuetoframeworkmapping',
            constraint=models.UniqueConstraint(fields=('canonical_issue', 'criterion'), name='unique_issue_to_framework_criterion'),
        ),
    ]
